### ISSUE TITLE
Add a LICENSE or COPYING file

### ISSUE THREAD

**Issue by mithro** [PrincetonUniversity/prga#1]
It would make it clear what the license this code is under and provide you a nice badge on the github repo. See example;
![image](https://user-images.githubusercontent.com/21212/51412909-0a377700-1bd2-11e9-90a1-bb436ce3999d.png)

![image](https://user-images.githubusercontent.com/21212/51412934-20453780-1bd2-11e9-950f-3a5c986c30aa.png)

**Comment by mithro** [comment]
@leon575777642 ping?

**Comment by angl-dev** [comment]
My advisor is still working with the univeristy on the licensing policies. I'll ask him how things are going.

**Comment by angl-dev** [comment]
Added! Woohoo! (BSD-3) @mithro
