### ISSUE TITLE
new blocks and bitstream

### ISSUE THREAD

**Issue by buddynohair** [PrincetonUniversity/prga#11]
Hello,

i try to generate a new custom block called "hard_logic_block" (similar as a DSP-block), which has the same level as club-block from the hierarchy , but it shows me an error.
<img width="1280" alt="截屏2020-09-06下午11 18 51" src="https://user-images.githubusercontent.com/66943123/92335474-7ca2e680-f097-11ea-9905-fedb5853e2e8.png">
<img width="1280" alt="截屏2020-09-06下午11 19 11" src="https://user-images.githubusercontent.com/66943123/92335478-81679a80-f097-11ea-9c93-dd1db0371ed8.png">

Besides, i still wanna ask something about Bitstream. I think the FPGA is successfully generated, but i can't find the bitstream file in the output files.

**Comment by angl-dev** [comment]
Hi @buddynohair , for the first question, I think you're missing a closing parenthesis at the end of the if condition.

As for bitstream file, if you are able to run the simulation and get the test passed message, you should find the bitstream file: `examples/target/{design}/{fpga}/{design}.memh`.

**Comment by buddynohair** [comment]
Hallo,

Thank you very much, i have found it.

Ang Li <notifications@github.com> 于2020年9月8日周二 上午8:33写道：
