### ISSUE TITLE
Build error on Ubuntu 20.04

### ISSUE THREAD

**Issue by mjc0608** [PrincetonUniversity/prga#24]
Hi, while building PRGA on Ubuntu 20.04, an error is encountered saying pyenv is not choosing the correct python version, then at a later stage, the installation script reports "Locking Failed" and crashes in a python command `/home/jcma/prga/prga.py/.venv/bin/python /home/jcma/.local/lib/python2.7/site-packages/pipenv/patched/notpip install --ignore-installed --no-user --prefix /tmp/pip-build-env-gksjbwmb/overlay --no-warn-script-location --no-binary :none: --only-bi
nary :none: -i https://pypi.org/simple -- setuptools wheel setuptools_scm`

Also attached the full log. 
[log.txt](https://github.com/PrincetonUniversity/prga/files/6516873/log.txt)

**Comment by angl-dev** [comment]
Hi @mjc0608 thanks for the notification.

This seems to be caused by an update of `pyenv`. I'll check it and get back to you soon.

**Comment by angl-dev** [comment]
Hi @mjc0608 could you pull the latest commit on the `release` branch? It should work now.

**Comment by mjc0608** [comment]
It works. Thanks!
