### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by dingzex** [PrincetonUniversity/prga#25]
ding@ding-desktop:~/PyFPGA/prga$ sudo ./envscr/install 
[INFO] PyFPGA install ......
[INFO] Using 'git': /usr/bin/git
[INFO] Using 'make': /usr/bin/make
[INFO] Using 'cmake': /usr/bin/cmake
[INFO] Using 'gcc': /usr/bin/gcc
[INFO] Locally-installed 'pyenv' found. Updating 'pyenv'
HEAD 目前位于 4ce52bd3 2.0.0-rc1
[INFO] 'pyenv' updated
[INFO] Activating locally-installed 'pyenv'
[INFO] 'pyenv' activated
[INFO] Installing Python 3.8.2 with 'pyenv'
[INFO] Downloading html .web Files....
Downloading Python-3.8.2.tar.xz...
-> https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tar.xz
Installing Python-3.8.2...

BUILD FAILED (Ubuntu 18.04 using python-build 2.0.0-rc1)

Inspect or clean up the working tree at /tmp/python-build.20210729192017.18966
Results logged to /tmp/python-build.20210729192017.18966.log

Last 10 log lines:
  File "/tmp/python-build.20210729192017.18966/Python-3.8.2/Lib/ensurepip/__init__.py", line 119, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/tmp/python-build.20210729192017.18966/Python-3.8.2/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 570, in _get_data
zipimport.ZipImportError: can't decompress data; zlib not available
Makefile:1186: recipe for target 'install' failed
make: *** [install] Error 1
ding@ding-desktop:~/PyFPGA/prga$

**Comment by dingzex** [comment]
After reinstalling today, there is still a post installation error. Can you ask me a question?
ding@ding-desktop:~/prga$ ./envscr/install 
[INFO] Using 'git': /usr/bin/git
[INFO] Using 'make': /usr/bin/make
[INFO] Using 'cmake': /usr/bin/cmake
[INFO] Using 'gcc': /usr/bin/gcc
[INFO] Active 'pyenv' found. Skipping installation/activation of 'pyenv'
[INFO] Installing Python 3.8.2 with 'pyenv'
Downloading Python-3.8.2.tar.xz...
-> https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tar.xz
error: failed to download Python-3.8.2.tar.xz

BUILD FAILED (Ubuntu 20.04 using python-build 2.0.4)

Results logged to /tmp/python-build.20210802002918.107335.log

Last 10 log lines:
/tmp/python-build.20210802002918.107335 ~/prga
curl: (6) Could not resolve host: www.python.org
ding@ding-desktop:~/prga$

**Comment by angl-dev** [comment]
Hi @dingzex sorry for the late reply.

The first log seems to suggest zlib is missing. The second log seems to suggest www.python.org is not accessible at the time of installation. Is it possible that your Ubuntu installation is missing certain packages or not connected to the network properly?

**Comment by dingzex** [comment]
Hello, thank you for your attention to my problem.
According to your reminder, I reinstalled zlib before pyenv, but there are still the above problems.
The network connection on my side should be normal, but the following problems are found:
ding@ding-desktop:~/prga$ ./envscr/install
[INFO] Using 'git': /usr/bin/git
[INFO] Using 'make': /usr/bin/make
[INFO] Using 'cmake': /usr/bin/cmake
[INFO] Using 'gcc': /usr/bin/gcc
[INFO] Active 'pyenv' found. Skipping installation/activation of 'pyenv'
[INFO] Installing Python 3.8.2 with 'pyenv'
Downloading Python-3.8.2.tar.xz...
-> https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tar.xz
Installing Python-3.8.2...
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 20.04 using python-build 2.0.4)

Inspect or clean up the working tree at /tmp/python-build.20210802194001.29248
Results logged to /tmp/python-build.20210802194001.29248.log

Last 10 log lines:
		$ensurepip --root=/ ; \
fi
/tmp/tmpsf1htkho/pip-19.2.3-py2.py3-none-any.whl/pip/_vendor/ipaddress.py:1106: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
/tmp/tmpsf1htkho/pip-19.2.3-py2.py3-none-any.whl/pip/_vendor/ipaddress.py:1106: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
Looking in links: /tmp/tmpsf1htkho
Collecting setuptools
Collecting pip
ERROR: pipenv 2021.5.29 requires certifi, which is not installed.
Installing collected packages: setuptools, pip
Successfully installed pip-19.2.3 setuptools-41.2.0

**Comment by angl-dev** [comment]
Hi @dingzex ,

A few things suspicous are: 
* WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
* ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?
* ERROR: pipenv 2021.5.29 requires certifi, which is not installed.

These are not really packages required by PRGA, but by pyenv, pipenv and python3. If they still do not work, you can install pyenv then pipenv on your own.

**Comment by angl-dev** [comment]
Two more things that may help:

* Always start with a clean repo after fixing any dependency problem and then run `envscr/install`, in case some partially-installed stuff are not cleaned up.
* As a reference, you can take a look at `https://github.com/PrincetonUniversity/prga/runs/3197318509?check_suite_focus=true` for the log of PRGA's CI installation on ubuntu 20.04

**Comment by dingzex** [comment]
Thank you very much for your help. I have successfully passed the compilation and can run completely.

Please give more advice on future study.
thank you.
![2021-08-03 22-04-27 的屏幕截图](https://user-images.githubusercontent.com/11873758/128030245-1d9c11f2-7ebd-466b-94ae-adaef0814b60.png)

**Comment by angl-dev** [comment]
Cool! I'll close this issue for now. If you have other questions with regard to the use or development of PRGA, please open another issue.
