### ISSUE TITLE
failed to find matching architecture model for '$_DFF_PP0'

### ISSUE THREAD

**Issue by WhiteStart** [PrincetonUniversity/prga#27]
![WechatIMG128](https://github.com/PrincetonUniversity/prga/assets/45161105/d167446e-7fbc-4192-8577-6befab6e4b96)

**Comment by angl-dev** [comment]
Hi, @WhiteStart 

Sorry for the delay.

Could you provide more info? Did you change anything (e.g., the generated Yosys synthesis script)? Yosys should not produce "$_DFF_PP0" cells. They should be replaced with ".latch".

**Comment by WhiteStart** [comment]
Thanks for your reply,this has been solved, I forgot to close the issue

**Comment by OlinLai** [comment]
> Thanks for your reply,this has been solved, I forgot to close the issue

@WhiteStart Hi! I met with the same problem. Could you please provide me with the solution of this error? Thanks!
