### ISSUE TITLE
Support Python 3!

### ISSUE THREAD

**Issue by mithro** [PrincetonUniversity/prga#3]
[Python 2 is dead](https://pythonclock.org/). Python 3 should be supported. It's pretty easy to support both 2.7 and 3 these days, but just supporting 3 is another option.

> The End Of Life date (EOL, sunset date) for Python 2.7 has been moved five years into the future, to 2020.

**Comment by angl-dev** [comment]
PRGA is now compatible with Python 2 and 3.
