### ISSUE TITLE
Add link from https://prga.rtfd.io to GitHub repository

### ISSUE THREAD

**Issue by mithro** [PrincetonUniversity/prga#4]
It would be good if you could get from the prga documentation to the github repository really easily.

I suggest the following;
 - [x] Add a link to the github repo on the navigation section.
 - [x] Add a link to the github repo on the front page.
 - [ ] Enable the "edit this page on github" functionality of rtd. (See https://github.com/SymbiFlow/prjxray/blob/master/docs/conf.py#L67-L75 for an example).

**Comment by mithro** [comment]
Poke :-)

Was just about to log this issue again....

**Comment by angl-dev** [comment]
Totally missed the notification for your last comment.

> * [ ]  Add a link to the github repo on the navigation section.

There is actually a link there but in the form of a watch button. I didn't figure out how to add a normal link there. I'm using the `alabaster` theme which seems to be a bit different from the `sphinx_rtd_theme`.

> * [x]  Add a link to the github repo on the front page.
> * [ ]  Enable the "edit this page on github" functionality of rtd. (See https://github.com/SymbiFlow/prjxray/blob/master/docs/conf.py#L67-L75 for an example).

"edit on github" seems to be a feature unique to the `sphinx_rtd_theme`.

**Comment by mithro** [comment]
I highly recommend using the sphinx_rtd_theme or the new [sphinx_materialdesign_theme](https://myyasuda.github.io/sphinx_materialdesign_theme/) over the alabaster theme.

**Comment by angl-dev** [comment]
Recommendation accepted :) Thanks!

**Comment by mithro** [comment]
Looks great!
