### ISSUE TITLE
Error while building fpga_tiny_k4_N2_8x8

### ISSUE THREAD

**Issue by kiranhollag** [PrincetonUniversity/prga#7]
Hi, I came across PRGA topic while searching for open source FPGA and EDA tools, looks really amazing; I am very new to these open-source tools and Python. While building **k4_N2_8x8** as per **docs/source/intro.rst** (**shorturl.at/iopAM**), I am facing following error.

python build.py
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from prga.api.context import *
ModuleNotFoundError: No module named 'prga'
make: *** [../../Makefile.in:10: ctx.pickled] Error 1

Installation was successful and before running the MAKE, **./envscr/activate** was also run without any issues.

I am missing something extremely important? Can anyone please help?

**Comment by kiranhollag** [comment]
@leon575777642 any thoughts on this?

**Comment by angl-dev** [comment]
Hi @kiranhollag ! Sorry for the late reply.

That seems to me like a python module installation problem. `prga.py` is not successfully installed into the virtual environment. I suggest you do the following:

1. go to `prga.py`, run `rm -rf .venv`. This cleans the previously installed Python virtual environment
2. Rerun `envscr/install` and save the entire log. Post the log here and I'll help you with the installation

**Comment by kiranhollag** [comment]
Hi @leon575777642  thank you for the reply.

Please find the attached log (while running envscr/install)
[prga_install_log.txt](https://github.com/PrincetonUniversity/prga/files/4710104/prga_install_log.txt)

Now facing "AttributeError: install_layout" @ different places.
FYI, I am using Ubuntu 20.04, just wanted to know are there any OS/Linux version dependencies?

Thanks, 
Kiran

**Comment by angl-dev** [comment]
Hi Kiran,
I noticed two things in the log:
1. Check the commit of your VTR installation and make sure it is consistent with the submodule in prga.
2. It seems the pipfile created in `prga.py` requires python 3.8. You may remove the `Pipefile` and `Pipfile.lock` in `prga.py` and rerun the installation. I'm not sure if that's why `bitarray` and `prga.py` failed to install, but worth a try.

By the way, are you using the `release` branch?

**Comment by kiranhollag** [comment]
Hi @leon575777642, Thanks again for the info.

1. VTR installation : `perl run_quick_test.pl` ran successfully, so it looks to be fine.
2. Reran the build with clean setup and "`PYTHON_VERSION=3.8.0`" in ./envscr/install, it took Python 3.8.0 for the local installation, but again hitting issue while building "**bitarray future hdlparse**"; this error is coming while "**installing -e**" .One thing I observed is, its taking cached bitarray-1.2.2.tar.gz, future-0.18.2.tar.gz etc; but this might be ok. VTR installation looks fine here too.  Please find the the log for reference [prga_install_log_failed_at_bitarray.txt](https://github.com/PrincetonUniversity/prga/files/4713246/prga_install_log_failed_at_bitarray.txt).

Regarding the Branch, : I had cloned it using "https://github.com/PrincetonUniversity/prga"

Thanks,
Kiran

**Comment by angl-dev** [comment]
Hi @kiranhollag , this might be an OS/compiler problem. I googled a bit and it seems upgrading `setuptools` and `pip` usually helps. This is a bit strange in our case, because the installation script installs `pyenv` to manage not only the python packages but also the python interpretter and pip themselves. Could you try activating the virtual environment manually, then run `pip install --upgrade setuptools pip`?

**Comment by kiranhollag** [comment]
Hi @leon575777642, Thanks for the info.

I am trying this option, I will let you know on the progress.

Thanks,
Kiran

**Comment by angl-dev** [comment]
By the way, another developer encountered some problems when installing VPR on Ubuntu 19.10 so he eventually used a VM to install prga. This is not the best option, but if other solutions don't work, you can give it a try.

**Comment by kiranhollag** [comment]
Hi @leon575777642 

Now I am able to solve this issue and it works perfectly fine on Ubuntu 20.04, there were few problems as listed below; detailed the resolution also so that it would be easier for a newcomer like me.

- Warnings on PIP file version like "Your Pipfile requires python_version 3.8, but you are using 3.7.2"
  [Resolution] : Python version number was corrected in the install file : PYTHON_VERSION=3.8.2
- pipenv issue 
    1. **pipenv** may not install sometimes, maybe because of the `if condition` @ **line no 98** in install file, this condition might get evaluated "TRUE" even if the PIPENV installed (globally) is an  incompatible version (say 3.6) 
    2. or Another error **PIP not found** might pop up
    3. or **PIPENV not found** might pop up
    [Resolution] : Added ${PWD}/pyenv/versions/${PYTHON_VERSION}/bin to PATH variable and installed PIPENV at the PRGA local directory without checking any condition 
- As per our previous comments, updating PIP and setup tools
  [Resolution] : Used `pip install --upgrade setuptools pip` in the install file
- With the above settings, the installation was successful and PRGA can be run in **batch/command flow**, but **EasyGL Graphics was disabled** because of  CMAKE's warning "**Could NOT find X11**" even after installing `libx11-dev`
    1. This issue is highlighted @ : https://github.com/LNIS-Projects/OpenFPGA/issues/42
    2. Used following commands to install CMAKE 3.12.0
        `<Removed earlier CMAKE, it was 3.16.x>`
        `wget https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh`
        `cd <to the download path>` #Usually its PWD
        `sudo ./cmake-3.12.0-Linux-x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local  `
        And reran(didn't delete any packages/files) `./envscr/install`, this time EasyGL Graphics was enabled and able to open VPR GUI as well

Attaching the Original([install_orig.txt](https://github.com/PrincetonUniversity/prga/files/4758661/install_orig.txt)) and the working([install_working.txt](https://github.com/PrincetonUniversity/prga/files/4758664/install_working.txt)) copy of install files
Thanks for all the information provided.

Regards,
Kiran

**Comment by angl-dev** [comment]
Hi @kiranhollag ,

Thanks a lot for looking into this issue. Could you create a pull request with your update on the install script? I'm working towards a new release and let's see if we can merge your changes into the new release!

**Comment by angl-dev** [comment]
Hi @kiranhollag ,

I've updated the scripts in the latest release and included the fixes you recommended. Thanks for looking into this!
